using Domain.Utils;

namespace Domain.Enumerators;

public enum BusinessErrorMessage
{
    [EnumDescription("USER_NOT_FOUND")]
    USER_NOT_FOUND = 1,

    [EnumDescription("INVALID_PASSWORD")]
    INVALID_PASSWORD = 2,

    [EnumDescription("NOT_FOUND")]
    NOT_FOUND = 3,

    [EnumDescription("INVALID_PAGE")]
    INVALID_PAGE = 4,

    [EnumDescription("INVALID_PARAMETER")]
    INVALID_PARAMETER = 5,

    [EnumDescription("DOCUMENT_ALREADY_USED")]
    DOCUMENT_ALREADY_USED = 6,

    [EnumDescription("NAME_ALREADY_USED")]
    NAME_ALREADY_USED = 7,

    [EnumDescription("INSTALLATION_NOT_BELONG_THIS_USER")]
    INSTALLATION_NOT_BELONG_THIS_USER = 8,

    [EnumDescription("INSTALLATION_ALREADY_EXISTS")]
    INSTALLATION_ALREADY_EXISTS = 9,

    [EnumDescription("FILE_ALREADY_EXISTS")]
    FILE_ALREADY_EXISTS = 10,

    [EnumDescription("FILE_NOT_FOUND")]
    FILE_NOT_FOUND = 11,

    [EnumDescription("SOMETHING_WENT_WRONG")]
    SOMETHING_WENT_WRONG = 12,

    [EnumDescription("INSTALLATION_NOT_FOUND")]
    INSTALLATION_NOT_FOUND = 13,

    [EnumDescription("RECOVERY_INVALID_TOKEN")]
    RECOVERY_INVALID_TOKEN = 14,

    [EnumDescription("USER_NOT_FOUND_OR_INVALID_PASSWORD")]
    USER_NOT_FOUND_OR_INVALID_PASSWORD = 15,

    [EnumDescription("EXPIRED_SIGN_TOKEN")]
    EXPIRED_SIGN_TOKEN = 16,

    [EnumDescription("INVALID_STEP")]
    INVALID_STEP = 17,

    [EnumDescription("INVALID_TOKEN")]
    INVALID_TOKEN = 18,

    [EnumDescription("INVALID_DOCUMENT_OR_RECOVERY_PASSWORD_TOKEN")]
    INVALID_DOCUMENT_OR_RECOVERY_PASSWORD_TOKEN = 18,

    [EnumDescription("USER_WITH_REPEAT_REGISTRATION_EMAIL")]
    USER_WITH_REPEAT_REGISTRATION_EMAIL = 19,

    [EnumDescription("USER_WITH_REPEAT_REGISTRATION_PHONE")]
    USER_WITH_REPEAT_REGISTRATION_PHONE = 20,

    [EnumDescription("USER_WITH_REPEAT_REGISTRATION_EMAIL_AND_PHONE")]
    USER_WITH_REPEAT_REGISTRATION_EMAIL_AND_PHONE = 21,

    [EnumDescription("INVALID_DDD_NUMBER")]
    INVALID_DDD_NUMBER = 22,

    [EnumDescription("SOME_VALUE_IS_MISSING")]
    SOME_VALUE_IS_MISSING = 23,

    [EnumDescription("ENUM_ERROR")]
    ENUM_ERROR = 24,

    [EnumDescription("PRODUCT_NOT_FOUND")]
    PRODUCT_NOT_FOUND = 25,

    [EnumDescription("ORDER_NOT_FOUND")]
    ORDER_NOT_FOUND = 26,

    [EnumDescription("CART_NOT_FOUND_OR_EMPTY")]
    CART_NOT_FOUND_OR_EMPTY = 27,

    [EnumDescription("ADDRESS_NOT_FOUND")]
    ADDRESS_NOT_FOUND = 28,

    [EnumDescription("EMAIL_ALREADY_USED")]
    EMAIL_ALREADY_USED = 29,

    [EnumDescription("CNPJ_ALREADY_USED")]
    CNPJ_ALREADY_USED = 30,

    [EnumDescription("COMPANY_NOT_FOUND")]
    COMPANY_NOT_FOUND = 31,

    [EnumDescription("COMPANY_ALREADY_REVIEWED")]
    COMPANY_ALREADY_REVIEWED = 32,

    [EnumDescription("COMPANY_NOT_APPROVED")]
    COMPANY_NOT_APPROVED = 33,

    [EnumDescription("ROLE_NOT_FOUND")]
    ROLE_NOT_FOUND = 34,

    [EnumDescription("ROLE_ALREADY_EXISTS")]
    ROLE_ALREADY_EXISTS = 35,

    [EnumDescription("CANNOT_MODIFY_SYSTEM_ROLE")]
    CANNOT_MODIFY_SYSTEM_ROLE = 36,

    [EnumDescription("MEMBER_NOT_FOUND")]
    MEMBER_NOT_FOUND = 37,

    [EnumDescription("MEMBER_ALREADY_EXISTS")]
    MEMBER_ALREADY_EXISTS = 38,

    [EnumDescription("CANNOT_REMOVE_OWNER")]
    CANNOT_REMOVE_OWNER = 39,

    [EnumDescription("PERMISSION_DENIED")]
    PERMISSION_DENIED = 40,

    [EnumDescription("TERMS_MUST_BE_ACCEPTED")]
    TERMS_MUST_BE_ACCEPTED = 41,

    [EnumDescription("MISSING_REQUIRED_DOCUMENTS")]
    MISSING_REQUIRED_DOCUMENTS = 42,

    [EnumDescription("INVITE_NOT_FOUND")]
    INVITE_NOT_FOUND = 43,

    [EnumDescription("INVITE_EXPIRED")]
    INVITE_EXPIRED = 44,

    [EnumDescription("INVITE_ALREADY_USED")]
    INVITE_ALREADY_USED = 45,

    [EnumDescription("INVITE_EMAIL_MISMATCH")]
    INVITE_EMAIL_MISMATCH = 46,

    [EnumDescription("SERVICE_NOT_FOUND")]
    SERVICE_NOT_FOUND = 47,

    [EnumDescription("SERVICE_CATEGORY_NOT_FOUND")]
    SERVICE_CATEGORY_NOT_FOUND = 48,
}
